version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PORT}:5432"
    volumes:
      - ${VOLUME_PATH}:/var/lib/postgresql/data
