name: branch_push_deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn lint
      # - run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -g yarn
      - run: yarn install
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PUBLIC_IP_ADDRESS }} >> ~/.ssh/known_hosts
      - name: Server deployment
        env:
          DEPLOYER_USERNAME: ${{ secrets.DEPLOYER_USERNAME }}
          PUBLIC_IP_ADDRESS: ${{ secrets.PUBLIC_IP_ADDRESS }}
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: npx shipit production deploy
